security:
    user:
    password: changeMe
    oauth2:
        resource:
            id: oauth2_id

spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

samlIdpMetadataLocation: classpath:/metadata/metadata.xml
samlAuthnRequestEntityId: entityId
samlAuthnRequestProviderName: providerName
keystoreLocation: classpath:/security/keystore.jks
keystoreDefaultKey: default
keystoreTokenSigningKey: oauth
keystorePassword: changeit
loginSuccessTargetUrl: /home
loginErrorTargetUrl: /auth-fail
logoutSuccessTargetUrl: /

server:
    port: ${serverPort:8443}
    ssl:
        key-store: ${keystoreLocation}
        key-store-password: ${keystorePassword}
        key-password: ${keystorePassword}