server:
    port: 8080

security:
    user:
    password: changeMe

oauth2:
    resource:
        id: oauth2_id

spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

samlIDPMetadataLocation: classpath:/metadata/metadata.xml
samlAuthnRequestEntityId: entityId
samlAuthnRequestProviderName: provideName
samlKeystoreLocation: classpath:/security/mykeystore.jks
samlKeystoreDefaultKey: default
samlKeystorePassword: changeit

loginSuccessTargetUrl: /home
loginErrorTargetUrl: /auth-fail
logoutSuccessTargetUrl: /