server:
  port: 8080

security:
  user:
    password: changeMe

  oauth2:
    resource:
      id: oauth2_id
      
  spring:
    mvc:
       view:
           prefix: /WEB-INF/views/
           suffix: .jsp
         
samlIDPMetadataLocation: classpath:/metadata/idp-meta.xml
samlAuthnRequestEntityId: urn:test:zmoore:doi:usgs:wma
samlAuthnRequestProviderName: urn:test:zmoore:doi:usgs:wma
samlKeystoreLocation: classpath:/security/ssocircleKeystore.jks
samlKeystoreDefaultKey: apollo
samlKeystorePassword: nalle123

loginSuccessTargetUrl: /home
loginErrorTargetUrl: /auth-fail
logoutSuccessTargetUrl: /