server:
  port: 8080

security:
  user:
    password: changeMe

  oauth2:
    resource:
      id: oauth2_id

samlIDPMetadataLocation: /metadata/FederationMetadata.xml
samlAuthnRequestEntityId: NWIS-RA-CHS-PROD
samlAuthnRequestProviderName: NWIS-RA-CHS-PROD
samlKeystoreLocation: /security/samlKeystore.jks
samlKeystoreDefaultKey: default
samlKeystorePassword: changeit